### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by hderp886** [warlof/slackbot#1]
While running composer update -

  ```
Problem 1
    - Installation request for eveseat/seat dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e -> satisfiable by eveseat/seat[dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - warlof/slackbot 0.3.3 requires eveseat/seat ^1.0 -> satisfiable by eveseat/seat[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Can only install one of: eveseat/seat[1.0.0, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.1, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.10, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.11, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.12, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.2, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.3, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.4, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.5, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.6, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.7, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.8, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Can only install one of: eveseat/seat[1.0.9, dev-27b2b4837608d866fc653e4f7eeaa6f472782e1e].
    - Installation request for warlof/slackbot >=0.3.3 -> satisfiable by warlof/slackbot[0.3.3].
```
I'm on seat 1.0.12, with a clean working install. Any thoughts?

**Comment by Bingmano** [comment]
I get the same issue with slackbot 0.3.5
`  Problem 1
    - Installation request for eveseat/seat dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c -> satisfiable by eveseat/seat[dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - warlof/slackbot 0.3.5 requires eveseat/seat ^1.0 -> satisfiable by eveseat/seat[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Can only install one of: eveseat/seat[1.0.0, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.1, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.10, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.11, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.12, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.2, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.3, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.4, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.5, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.6, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.7, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.8, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Can only install one of: eveseat/seat[1.0.9, dev-f50c26f892004282e394f1ff3a8a1b1de8726d5c].
    - Installation request for warlof/slackbot ^0.3.5 -> satisfiable by warlof/slackbot[0.3.5].
`

**Comment by warlof** [comment]
I don't know if it's due to seat package or for stable status.
I've remove eveseat/seat from dependencies in 0.4.0 in addition to a quick new feature (public filter)

I'm working on my own rtm service since the status cannot be set to stable due to `jclg/php-slack-bot` which is used in Slack Daemon Service.

I'll try to fix this as soon as possible
