### ISSUE TITLE
User kick from channel, No action taken

### ISSUE THREAD

**Issue by Skullmaker90** [warlof/slackbot#3]
Looks as though the bot is attempting to kick a user (superuser roles) from a channel but is either:
    - Not succeeding in the first place.
    - Or not attempting and just logging.
 
The actual bug here is that all channels are public filtered and users are still trying to be kicked.

**Comment by Skullmaker90** [comment]
Quick update it seems as though it's trying to kick the user from all channels their a member of.

**Comment by warlof** [comment]
Which version are you running ?
Last is 0.7.1 and provide fix for logging and kicking token owner.

Plus
- how many api keys this user is owning ?
- how many are still valid
- how many pledged account are related to those API

**Comment by Skullmaker90** [comment]
Let me update and see if the issue persists, but to answer the question:
    - 1 Api Key,
    - Still valid
    - Only one

**Comment by warlof** [comment]
take care of this note https://github.com/warlof/slackbot/blob/master/CHANGELOG.md#version-070 if you're upgrade from any version previous to 0.7.x

**Comment by Skullmaker90** [comment]
Doesn't look to have been it, are there any dumps I could give you to help with the issue? I've upgraded to 7.0.1 successfully.

**Comment by warlof** [comment]
https://github.com/warlof/slackbot/wiki/Debug-Query-Reports

**Comment by warlof** [comment]
Any news about this issue ?

**Comment by Skullmaker90** [comment]
Apologies, currently migrating to a new server I'll update when finished.

**Comment by warlof** [comment]
Any news about this issue ?
