### ISSUE TITLE
Slack Receptionist 

### ISSUE THREAD

**Issue by ysm1mh** [warlof/slackbot#6]
according to the wiki. 

`If SeAT is not already knowing the Slack member ID, Slack Receptionist will send an invite using the associated user mail address`

the mails are not being send.  cant even find any log what so ever to check.

can i get some advice / help on this matter?

**Comment by warlof** [comment]
Thanks for pointing the outdated information in the Wiki.

This feature is non longer supported since 2.x.x version https://github.com/warlof/slackbot/blob/master/CHANGELOG.md#version-200-announcement due to Api constraint and plugin design modification.
