### ISSUE TITLE
Slack ratelimiter

### ISSUE THREAD

**Issue by hderp886** [warlof/slackbot#7]
I have about 150 users now on Seat using Slack.
I receive strings of errors of ratelimited rejected requests for exceeding the one request per second guideline.

**Comment by warlof** [comment]
Since 2.0.1, the bot is using a lot redis in order to keep sync up between Slack and SeAT.
Are you clearing offen your cache ?

If not, I need to find a way to seed a job every seconds :/

**Comment by hderp886** [comment]
Update on this. Currently running Seat 2.0.15 and latest slackbot release.
Cleared cache and waited for scheduled job.

130 active members in Slack. Ratelimiter hit for 38 of the scheduled jobs during slack:update the first time it ran. Job is now scheduled for every 10 minutes, no failures since then.

**Comment by warlof** [comment]
2.1.8 should be released this week-end with a time countdown of 1sec for every Slack request.
